### ISSUE TITLE
[Q | RR8.6.4] Google Chrome java.lang.SecurityException android.permission.INTERACT_ACROSS_USERS

### ISSUE THREAD

**Issue by Enkidu70** [oasisfeng/island#186]
Hi!

I need some help please.

I just installed Island on my OnePlus 6T, now with Android 10, Resurrection Remix 8.6.4, rooted (latest Magisk).

Directly after initiating Island and basic apps are shown, when I try to start Chrome, I always get an FC.

I tried creating an new Island profile/workspace ecc. but always the same.
Also no hits in Google concerning this error.

Any hint is very welcome!

Tnx in advance,
Enkidu

```
java.lang.SecurityException: get application info:  Neither user 1110361 nor current process has android.permission.INTERACT_ACROSS_USERS.
at android.os.Parcel.createException(Parcel.java:2071)
at android.os.Parcel.readException(Parcel.java:2039)
at android.os.Parcel.readException(Parcel.java:1987)
at  android.content.IClipboard$Stub$Proxy.getPrimaryClipDescription(IClipboard.java:360) 
at android.content.ClipboardManager.getPrimaryClipDescription(ClipboardManager.java:152) 
at org.chromium.chrome.browser.app.ChromeActivity.onWindowFocusChanged(chromium-TrichromeChromeGoogle.aab-stable-432409333:8) 
at kJ3.onWindowFocusChanged(chromium-TrichromeChromeGoogle.aab-stable-432409333:1) 
at Pe.invoke(chromium-TrichromeChromeGoogle.aab-stable-4 32409333:3) 
at java.lang.reflect.Proxy.invoke(Proxy.java:1006) 
at $Proxy0.onWindowFocusChanged(Unknown Source) 
at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1694) 
at android.view.View. dispatchWindowFocusChanged(View.java 114227) 
at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1480) 
at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootimpl.java:2940) 
at android.view.ViewRootImpl.access$1100(ViewRootlmpl.jav a:146) 
at android.view. ViewRootImpISViewRootHandler.handleMessage(ViewRootimpl.java:4700) 
at android.os.Handler.dispatchMessage(Handler.java:107) 
at android.os.Looper.loop(Looper.java:214) 
at android.app.ActivityThread.main(ActivityThread.java: 7398) 
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimelnitSMethodAndArgsCaller. un(Runtimeltnit.java:493) 
at com.android.internal.os.Zygotelnit.main(Zygotelnit.java: 940) 

Caused by: android.os.RemoteException: Remote stack trace: 
at android.app.ContextImpl.enforce(ContextIlmpl.java: 1896) 
at android.app.Contextimpl.enforceCallingOrSelfPermission(ContextIlmpl.java:1924) 
at com.android.server.pm.permission.PermissionManagerSerice.enforceCrossUserPermission(PermissionManagerService.java:2939) 
at com.android.server.pm.permission.PermissionManagerSer ice.access$2100(PermissionManagerService.java:122) 
at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServicelnternallmpl.enforceCrossUerPermission(PermissionManagerService.java:3146)
```

![Screenshot_20210123-222802676](https://user-images.githubusercontent.com/1456895/105614996-6e96fd80-5dcd-11eb-82f5-ac85ff066832.jpg)

![Screenshot_20210123-222833534](https://user-images.githubusercontent.com/1456895/105614984-58893d00-5dcd-11eb-8787-4876c657f63a.jpg)

**Comment by oasisfeng** [comment]
Seems like your Chrome is not a system app?

Maybe you can try shell command "pm grant com.android.chrome android.permission.INTERACT_ACROSS_USERS".

**Comment by Neywiny** [comment]
This does not work for I would assume the vast majority of apps. On android 8 I get:
`Operation not allowed: java.lang.SecurityException: Package [app] has not requested permission android.permission.INTERACT_ACROSS_USERS`

Which is in line with the documentation for that command. Only permissions requested (presumably in the manifest) can be granted.
