### ISSUE TITLE
解冻Island中的App时抛错 Error shuttling class

### ISSUE THREAD

**Issue by Shihira** [oasisfeng/island#191]
```
02-26 16:40:00.778 20182 31002 D Island.PIS: [0] Retrieved shuttle for profile 10
02-26 16:40:00.782  1219  1381 D BaseRestrictionMgr: Package: com.oasisfeng.island, userid: 10, hostingType: broadcast is Restricted by policy: 2 caller is: null
02-26 16:40:00.783 20182 20182 E Island.Apps: Unexpected internal error
02-26 16:40:00.783 20182 20182 E Island.Apps: java.lang.RuntimeException: Error shuttling class com.oasisfeng.island.controller.IslandAppControl$unfreezeAndLaunch$failure$1 (code 0)
02-26 16:40:00.783 20182 20182 E Island.Apps:   at com.oasisfeng.island.shuttle.PendingIntentShuttle$Companion.resume(SourceFile:1)
02-26 16:40:00.783 20182 20182 E Island.Apps:   at com.oasisfeng.island.shuttle.PendingIntentShuttle$Companion$shuttle$$inlined$suspendCoroutine$lambda$1.onSendFinished(SourceFile:2)
02-26 16:40:00.783 20182 20182 E Island.Apps:   at android.app.PendingIntent$FinishedDispatcher.run(PendingIntent.java:250)
02-26 16:40:00.783 20182 20182 E Island.Apps:   at android.app.PendingIntent$FinishedDispatcher.performReceive(PendingIntent.java:244)
02-26 16:40:00.783 20182 20182 E Island.Apps:   at android.content.IIntentReceiver$Stub.onTransact(IIntentReceiver.java:110)
02-26 16:40:00.783 20182 20182 E Island.Apps:   at android.os.Binder.execTransactInternal(Binder.java:1056)
02-26 16:40:00.783 20182 20182 E Island.Apps:   at android.os.Binder.execTransact(Binder.java:1029)
```

手机是Samsung S10 SM-G9730，Android 10。现在所有冻结的App都无法Unlock，但是进Scoped Settings里Repair之后能会好一段时间，过一段时间（锁屏十几分钟？）之后就会又坏掉。

Thanks.

**Comment by oasisfeng** [comment]
此问题应已修复。如果仍然存在，请在下面回复。
