### ISSUE TITLE
Island 5.3 - cannot freeze/unfreeze apps in the island

### ISSUE THREAD

**Issue by iuim-xim** [oasisfeng/island#206]
After recent update to Island 5.3, there is a severe problem - I cannot freeze/unfreeze apps in the island.
The system information is listed below.
. Android 9 / MIUI 12.1

**Comment by iuim-xim** [comment]
Log from Android system:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.oasisfeng.island/com.oasisfeng.island.shortcut.IslandAppShortcut$ShortcutLauncher}: java.lang.IllegalStateException: Shuttle not ready
       at android.app.ActivityThread.performLaunchActivity(Unknown Source:591)
       at android.app.ActivityThread.handleLaunchActivity(Unknown Source:36)
       at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:57)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:99)
       at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:34)
       at android.app.ActivityThread$H.handleMessage(Unknown Source:43)
       at android.os.Handler.dispatchMessage(Unknown Source:21)
       at android.os.Looper.loop(Unknown Source:210)
       at android.app.ActivityThread.main(Unknown Source:107)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
       at com.android.internal.os.ZygoteInit.main(Unknown Source:281)
 Caused by: java.lang.IllegalStateException: Shuttle not ready
       at com.oasisfeng.island.shuttle.Shuttle.shuttle(SourceFile:11)
       at com.oasisfeng.island.shuttle.Shuttle.launch(SourceFile:3)
       at com.oasisfeng.island.shortcut.IslandAppShortcut$ShortcutLauncher.launch0(SourceFile:21)
       at com.oasisfeng.island.shortcut.IslandAppShortcut$ShortcutLauncher.launch(SourceFile:3)
       at com.oasisfeng.island.shortcut.IslandAppShortcut$ShortcutLauncher.onNewIntent(SourceFile:4)
       at com.oasisfeng.island.shortcut.IslandAppShortcut$ShortcutLauncher.onCreate(SourceFile:1)
       at android.app.Activity.performCreate(Unknown Source:16)
       at android.app.Activity.performCreate(Unknown Source:1)
       at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
       at android.app.ActivityThread.performLaunchActivity(Unknown Source:368)
       ... 11 more`

**Comment by AswinKrishnan** [comment]
> Log from Android system:
> `java.lang.RuntimeException: Unable to start activity ComponentInfo{com.oasisfeng.island/com.oasisfeng.island.shortcut.IslandAppShortcut$ShortcutLauncher}: java.lang.IllegalStateException: Shuttle not ready at android.app.ActivityThread.performLaunchActivity(Unknown Source:591) at android.app.ActivityThread.handleLaunchActivity(Unknown Source:36) at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:57) at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:99) at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:34) at android.app.ActivityThread$H.handleMessage(Unknown Source:43) at android.os.Handler.dispatchMessage(Unknown Source:21) at android.os.Looper.loop(Unknown Source:210) at android.app.ActivityThread.main(Unknown Source:107) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11) at com.android.internal.os.ZygoteInit.main(Unknown Source:281) Caused by: java.lang.IllegalStateException: Shuttle not ready at com.oasisfeng.island.shuttle.Shuttle.shuttle(SourceFile:11) at com.oasisfeng.island.shuttle.Shuttle.launch(SourceFile:3) at com.oasisfeng.island.shortcut.IslandAppShortcut$ShortcutLauncher.launch0(SourceFile:21) at com.oasisfeng.island.shortcut.IslandAppShortcut$ShortcutLauncher.launch(SourceFile:3) at com.oasisfeng.island.shortcut.IslandAppShortcut$ShortcutLauncher.onNewIntent(SourceFile:4) at com.oasisfeng.island.shortcut.IslandAppShortcut$ShortcutLauncher.onCreate(SourceFile:1) at android.app.Activity.performCreate(Unknown Source:16) at android.app.Activity.performCreate(Unknown Source:1) at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3) at android.app.ActivityThread.performLaunchActivity(Unknown Source:368) ... 11 more`

Same Issue here !  Will not let me neither unfreeze any frozen apps  or freeze active apps, all started after the recent update !
