### ISSUE TITLE
Cross-Land Privileges in Google Calendar Breaks after a period of time.

### ISSUE THREAD

**Issue by reuter** [oasisfeng/island#221]
The Cross land privileges for Calendar work for a while after setting up the profile, but after a few weeks, it just randomly stops working and I get a Sync Error inside the Google Calendar app.
Using a Samsung S21 Ultra

I have tried repairing the island, the Cross-land privilege for Calendar is enabled. I have cleared the cache, data, and reinstalled the Google Calendar app on both the mainland and island. I even tried clearing the Dalvik cache on the phone. As soon as I reinstall the Calendar app in the island and set it up again, as soon as I enable the Personal Calendars to be shown, it gives me the "Sync Error" message. I've been able to resolve in the past, but only after several days of uninstalling and reinstalling the Calendar apps, blowing away the profiles, and reinstalling Island. Even then, I have to do it a few times before it resolves. I'm not sure what it is I do in the end that finally gets it working again.

Here is the logs from what looks to be the error

```
05-19 09:20:09.306  1254  4926 W PackageManager: query intent receivers: Requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS or android.permission.INTERACT_ACROSS_PROFILES.
05-19 09:20:09.306  2201  9013 E CrossProfileSender: MissingApiException when trying to bind
05-19 09:20:09.306  2201  9013 E CrossProfileSender: com.google.android.enterprise.connectedapps.exceptions.MissingApiException: Error binding to other profile
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at cal.put.run(Unknown Source:23)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at java.lang.Thread.run(Thread.java:923)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: Caused by: java.lang.reflect.InvocationTargetException
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at java.lang.reflect.Method.invoke(Native Method)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at cal.put.run(Unknown Source:21)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	... 6 more
05-19 09:20:09.306  2201  9013 E CrossProfileSender: Caused by: java.lang.SecurityException: query intent receivers: Requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS or android.permission.INTERACT_ACROSS_PROFILES.
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at android.os.Parcel.createException(Parcel.java:2369)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at android.os.Parcel.readException(Parcel.java:2352)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at android.os.Parcel.readException(Parcel.java:2294)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at android.app.IActivityManager$Stub$Proxy.bindIsolatedService(IActivityManager.java:6860)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1913)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:1853)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	at android.content.ContextWrapper.bindServiceAsUser(ContextWrapper.java:793)
05-19 09:20:09.306  2201  9013 E CrossProfileSender: 	... 8 more
05-19 09:20:09.307  2201  9013 W CrossProfileLogging: Failed cross profile call.
05-19 09:20:09.307  2201  9013 W CrossProfileLogging: com.google.android.enterprise.connectedapps.exceptions.UnavailableProfileException: Missing API
05-19 09:20:09.307  2201  9013 W CrossProfileLogging: 	at cal.pvf.h(PG:2)
05-19 09:20:09.307  2201  9013 W CrossProfileLogging: 	at cal.put.run(Unknown Source:27)
05-19 09:20:09.307  2201  9013 W CrossProfileLogging: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
05-19 09:20:09.307  2201  9013 W CrossProfileLogging: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-19 09:20:09.307  2201  9013 W CrossProfileLogging: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
05-19 09:20:09.307  2201  9013 W CrossProfileLogging: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-19 09:20:09.307  2201  9013 W CrossProfileLogging: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-19 09:20:09.307  2201  9013 W CrossProfileLogging: 	at java.lang.Thread.run(Thread.java:923)

```

**Comment by oasisfeng** [comment]
According to the logcat, it's not related to the cross-land privilege functionality.

If the Google Calendar is a (bundled) system app, this should not happen generally. But you can still try re-granting the permission required in ADB shell:

`pm grant com.google.android.calendar android.permission.INTERACT_CROSS_USERS`

**Comment by reuter** [comment]
Just gave it a shot, this is the error that comes back.

```
Exception occurred while executing 'grant':
java.lang.IllegalArgumentException: Unknown permission: android.permission.INTERACT_CROSS_USERS
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1541)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1501)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1493)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2338)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:261)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26695)
        at android.os.Binder.shellCommand(Binder.java:965)
        at android.os.Binder.onTransact(Binder.java:839)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5206)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5323)
        at android.os.Binder.execTransactInternal(Binder.java:1195)
        at android.os.Binder.execTransact(Binder.java:1159)
```

**Comment by reuter** [comment]
Weirdly, I just discovered that a reboot will randomly fix it (won't always fix it) when it comes up.

**Comment by oasisfeng** [comment]
> Just gave it a shot, this is the error that comes back.
> 
> ```
> Exception occurred while executing 'grant':
> java.lang.IllegalArgumentException: Unknown permission: android.permission.INTERACT_CROSS_USERS
>         at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1541)
>         at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1501)
>         at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1493)
>         at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2338)
>         at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:261)
>         at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
>         at android.os.ShellCommand.exec(ShellCommand.java:44)
>         at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26695)
>         at android.os.Binder.shellCommand(Binder.java:965)
>         at android.os.Binder.onTransact(Binder.java:839)
>         at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5206)
>         at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5323)
>         at android.os.Binder.execTransactInternal(Binder.java:1195)
>         at android.os.Binder.execTransact(Binder.java:1159)
> ```

Sorry, it should be "android.permission.INTERACT_**A**CROSS_USERS", my mistake.

**Comment by reuter** [comment]
I finally found a repeatable workaround for this.
It seems liek any time I get an update to the OS, this breaks. So, after the update, i discovered I can boot into recovery mode and run "Repair Apps" and that seems to fix it until the next update breaks it.
