### ISSUE TITLE
Island 5.4.3 - cannot freeze/unfreeze apps in the island

### ISSUE THREAD

**Issue by iuim-xim** [oasisfeng/island#222]
The function "freeze/unfreeze app" in the island still does not work.
The system information is listed below.
. Android 9 / MIUI 12.1

System log as below.
> java.lang.IllegalStateException: Shuttle not ready
       at com.oasisfeng.island.shuttle.Shuttle.shuttle(SourceFile:4)
       at com.oasisfeng.island.shuttle.Shuttle.invoke(SourceFile:3)
       at com.oasisfeng.island.mobile.databinding.AppEntryBindingImpl._internalCallbackOnClick(SourceFile:11)
       at com.oasisfeng.island.mobile.generated.callback.OnClickListener.onClick(SourceFile:1)
       at com.oasisfeng.android.databinding.adapters.TextViewDrawableClickBindingAdapter$1.onTouch(SourceFile:13)
       at android.view.View.dispatchTouchEvent(Unknown Source:79)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:108)
       at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:523)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
       at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:523)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
       at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:523)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
       at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:523)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
       at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:523)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
       at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:523)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
       at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:523)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(Unknown Source:0)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(Unknown Source:2)
       at android.app.Activity.dispatchTouchEvent(Unknown Source:13)
       at android.view.WindowCallbackWrapper.dispatchTouchEvent(Unknown Source:2)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(Unknown Source:20)
       at android.view.View.dispatchPointerEvent(Unknown Source:9)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(Unknown Source:25)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(Unknown Source:21)
       at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:21)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:6)
       at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
       at android.view.ViewRootImpl$AsyncInputStage.forward(Unknown Source:10)
       at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
       at android.view.ViewRootImpl$AsyncInputStage.apply(Unknown Source:7)
       at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:25)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:6)
       at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
       at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
       at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:25)
       at android.view.ViewRootImpl.deliverInputEvent(Unknown Source:65)
       at android.view.ViewRootImpl.doProcessInputEvents(Unknown Source:69)
       at android.view.ViewRootImpl.enqueueInputEvent(Unknown Source:37)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(Unknown Source:7)
       at android.view.InputEventReceiver.dispatchInputEvent(Unknown Source:207)
       at android.os.MessageQueue.nativePollOnce(Native Method)
       at android.os.MessageQueue.next(Unknown Source:19)
       at android.os.Looper.loop(Unknown Source:64)
       at android.app.ActivityThread.main(Unknown Source:107)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
       at com.android.internal.os.ZygoteInit.main(Unknown Source:274)

**Comment by oasisfeng** [comment]
Please try "Repaire" in scoped settings of Island.

**Comment by iuim-xim** [comment]
> Please try "Repaire" in scoped settings of Island.

The "freeze/unfreeze" functions work well after the "Repair" operation.
Thanks for the answer.
