### ISSUE TITLE
Demigod mode Android 12 Beta

### ISSUE THREAD

**Issue by clyso** [oasisfeng/island#240]
activating Demigod mode on Android 12 shows error. But after Reboot Demigod Mode seems to work as I can freeze Apps in Mainland:
```
redfin:/ $ dpm set-profile-owner --user 0 --name Mainland com.oasisfeng.island.fdroid/com.oasisfeng.island.IslandDeviceAdminReceiver

Exception occurred while executing 'set-profile-owner':
java.lang.IllegalStateException: Not allowed to change provisioning state unless current provisioning state is unmanaged, and new state is finalized.
    at com.android.server.devicepolicy.DevicePolicyManagerService.setUserProvisioningState(DevicePolicyManagerService.java:8839)
    at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetProfileOwner(DevicePolicyManagerServiceShellCommand.java:297)
    at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:91)
    at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
    at android.os.ShellCommand.exec(ShellCommand.java:38)
    at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:9585)
    at android.os.Binder.shellCommand(Binder.java:950)
    at android.os.Binder.onTransact(Binder.java:834)
    at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6949)
    at android.os.Binder.execTransactInternal(Binder.java:1184)
    at android.os.Binder.execTransact(Binder.java:1143)
```
```
pm list users

Users:
    UserInfo{0:Eigentümer:c13} running
    UserInfo{10: Island :1030} running
```

see https://gitlab.com/secure-system/Insular/-/issues/32

**Comment by oasisfeng** [comment]
That's kind of new restriction enforced in Android 12. Until the AOSP source code is released, we cannot know the reason behind that.

**Comment by oasisfeng** [comment]
After testing, I can confirm that error message can be safely ignored.

**Comment by Pervases** [comment]
> After testing, I can confirm that error message can be safely ignored.

I confirmed this with POCO X3 Pro on MIUI Global 13.0.4 Stable (SJUMIXM).

**Comment by scruel** [comment]
I met this when I try to set the owner to island again after revoked the owner permission which granted before.

In order to be sure, after got this error, go island to revoke the owner permission, then re-execute grant command again, then you shall see "Success".
