### ISSUE TITLE
Island apps don't open after first reboot

### ISSUE THREAD

**Issue by KaMyKaSii** [oasisfeng/island#271]
ASUS Zenfone 4, Android 9.
The apps only work on the current boot after creating the Island. After the first reboot, no apps open anymore. Trying to restore the Island doesn't work, I left it for more than 12 hours without success. Below is the stack trace of one of the apps and attached is a logcat. Apparently the problem has to do with encryption, my device uses FDE (full disk encryption) with the need to enter the password at boot enabled. If you need a logcat during the first reboot, I can provide it.  Thank you!
```
FATAL EXCEPTION: main
Process: com.shopee.br, PID: 17461
java.lang.RuntimeException: Unable to create application com.shopee.app.application.ShopeeApplication_: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5930)
	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:198)
	at android.app.ActivityThread.main(ActivityThread.java:6732)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:419)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:404)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:181)
	at com.shopee.app.data.store.z0.l(SourceFile:2)
	at com.shopee.app.util.client.ClientUtil$b.g(SourceFile:1)
	at com.shopee.app.ui.home.native_home.configs.HomePageConfigure.f(SourceFile:1)
	at com.shopee.app.application.j2.onCreate(SourceFile:8)
	at com.shopee.app.application.ShopeeApplication_.onCreate(SourceFile:2)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
	... 8 more
```
[islandissue.txt](https://github.com/oasisfeng/island/files/7180051/islandissue.txt)

**Comment by KaMyKaSii** [comment]
Here is the log during boot after reboot
[liveboot.log](https://github.com/oasisfeng/island/files/7195554/liveboot.log)
