### ISSUE TITLE
Island apps open android.permission

### ISSUE THREAD

**Issue by Dog404** [oasisfeng/island#274]
OP7Pro Andrid11 aosp 
msg: java.lang.SecurityException: get application info: Requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS.
stacktrace: java.lang.SecurityException: get application info: Requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS.
at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
at android.os.Parcel.createException(Parcel.java:2357)
at android.os.Parcel.readException(Parcel.java:2340)
at android.os.Parcel.readException(Parcel.java:2282)
at android.content.IClipboard$Stub$Proxy.getPrimaryClipDescription(IClipboard.java:360)
at android.content.ClipboardManager.getPrimaryClipDescription(ClipboardManager.java:151)
at E42.getPrimaryClipDescription(chromium-ChromePublic.apk-stable-96105315:1)
at WC1.c(chromium-ChromePublic.apk-stable-96105315:1)
at org.chromium.chrome.browser.app.ChromeActivity.onWindowFocusChanged(chromium-ChromePublic.apk-stable-96105315:8)
at org.chromium.chrome.browser.ChromeTabbedActivity.onWindowFocusChanged(chromium-ChromePublic.apk-stable-96105315:1)
at Ue.onWindowFocusChanged(chromium-ChromePublic.apk-stable-96105315:1)
at gi.invoke(chromium-ChromePublic.apk-stable-96105315:3)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy1.onWindowFocusChanged(Unknown Source)
at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1693)
at android.view.View.dispatchWindowFocusChanged(View.java:14582)
at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1502)
at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:3262)
at android.view.ViewRootImpl.access$1200(ViewRootImpl.java:194)
at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5053)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7666)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by oasisfeng** [comment]
When did that happen?

**Comment by Hydra119** [comment]
> When did that happen?

As an Island User, assuming that this _is_ _your_ forum, and without knowing very much about the code, or about how actual coding works, in general, beyond what I skimmed of the OP's post, I'm curious to know the implications of this?

Seems like the Android OS is now asking Island for new security permissions? Or no...?

**Comment by DroidFreak32** [comment]
@Dog404 Did you have a "clipboard access alerts" feature enabled on your custom ROM when you faced this issue?
The app, when it requests for clipboard access will trigger this crash since this custom ROM feature probably cannot determine what is the app (since it is in an isolated environement). Disabling this feature fixed this issue for me.

**Comment by lfom** [comment]
I had a bunch of apps crashing when using Island/Work Profile, and indeed disabling "clipboard access alerts" fixed the problem (A11 custom ROM). Thanks, @DroidFreak32!

**Comment by H-saeedi** [comment]
در تاریخ شنبه ۷ ژانویهٔ ۲۰۲۳،‏ ۲۰:۲۸ lfom ***@***.***> نوشت:

**Comment by HidingCherry** [comment]
I had an equivalent issue but subtle - there was no app crash.
I tried to unfreeze the Contacts App, but there was a package manager error.
I had to use the following line:

`adb shell pm grant com.oasisfeng.island android.permission.INTERACT_ACROSS_USERS`

source: https://www.reddit.com/r/tasker/comments/k6lpmc/project_sharehowto_integrating_tasker_with_island/
