### ISSUE TITLE
华为mate10 ALP 经过一阵频繁的重启后 island创建的分身应用无法打开或是说闪退

### ISSUE THREAD

**Issue by caseci** [oasisfeng/island#309]
以前正常使用的时候开启工作模式的时候会要求输入锁屏密码, 现在不需要就能直接打开但是app好像并没有真的被授权解冻.  开启工作模式后别的一切需要调用锁屏密码的安全验证操作都是在输入正确密码后闪退, 关闭后才能正常使用
如果想要创建新的应用的话,一开始会显示Internal error: Shuttle not ready  在来到官网后首先按照https://island.oasisfeng.com/files
输入了pm grant com.oasisfeng.island android.permission.INTERACT_ACROSS_USERS
但是没有任何反馈
又进行了一系列操作后 创建应用的话手机提示Internal error: Unknown authority 11@com.oasisfeng.island.shuttle
 如果执行HWALP:/ $ dpm set-profile-owner --user 10 com.oasisfeng.island/.IslandDeviceAdminReceiver
显示java.lang.IllegalStateException: User must be running and unlocked
        at android.os.Parcel.createException(Parcel.java:2079)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.removeActiveAdmin(IDevicePolicyManager.java:8151)
        at com.android.commands.dpm.Dpm.runSetProfileOwner(Dpm.java:237)
        at com.android.commands.dpm.Dpm.onRun(Dpm.java:118)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:56)
        at com.android.commands.dpm.Dpm.main(Dpm.java:41)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
但是HWALP:/ $ pm list users
Users:
        UserInfo{0:Owner:13} running
        UserInfo{10:壶中界:30} running
        UserInfo{128:分身应用:4000010} running
我想知道如何重新调用安全验证正常的解锁工作空间 恢复使用? 或是说有别的解决方法?

**Comment by caseci** [comment]
另外输入HWALP:/ $ dumpsys activity | grep -i run的话,最后会显示
ACTIVITY MANAGER RUNNING PROCESSES (dumpsys activity processes)
    User #0: state=RUNNING_UNLOCKED
    User #10: state=RUNNING_LOCKED
    User #128: state=RUNNING_UNLOCKED

同时如果现在手机上关闭工作模式时输入pm list users
Users:
        UserInfo{0:Owner:13} running
        UserInfo{10:壶中界:b0}
        UserInfo{128:分身应用:4000010} running
有什么办法解锁应用吗

**Comment by oasisfeng** [comment]
能通过正常 UI 流程创建 Island 的话，非常不建议使用 ADB shell 手动创建，在一些设备上会带来潜在的复杂问题。

正常 UI 流程创建的 Island 是收到 Android CTS 兼容性认证保证的。

**Comment by caseci** [comment]
当初确实是按照正常的流程创建的, 但是手机可能是由于电源按键或是别的某些故障导致频繁的重启, 开机后就发现出现了故障无法打开分身应用

**Comment by caseci** [comment]
> 能通过正常 UI 流程创建 Island 的话，非常不建议使用 ADB shell 手动创建，在一些设备上会带来潜在的复杂问题。
> 
> 正常 UI 流程创建的 Island 是收到 Android CTS 兼容性认证保证的。

有什么办法能在不删除工作空间的情况下重新走一遍流程创建一次吗?

**Comment by caseci** [comment]
猜测是在手机不断重启的时候, 安全认证相关的模块出现了缺失?或是某些组件的启动顺序问题?

**Comment by caseci** [comment]
之前忘记说了: 系统是EMUI10.0.0     island版本是5.4.3

**Comment by caseci** [comment]
话说island是怎么调用系统的安全验证授权来解锁用户资料的呢?

其实和这个类似的问题在这次故障之前就已经有过, 有时有些分身应用冻结后重新解冻的时候会发生闪退, 无法打开应用, 必须关闭工作模式然后重新输入锁屏密码开启, 就好像之前冻结的这个过程没有走完一样

**Comment by oasisfeng** [comment]
> 另外输入HWALP:/ $ dumpsys activity | grep -i run的话,最后会显示 ACTIVITY MANAGER RUNNING PROCESSES (dumpsys activity processes) User #0: state=RUNNING_UNLOCKED User #10: state=RUNNING_LOCKED User #128: state=RUNNING_UNLOCKED
> 
> 同时如果现在手机上关闭工作模式时输入pm list users Users: UserInfo{0:Owner:13} running UserInfo{10:壶中界:b0} UserInfo{128:分身应用:4000010} running 有什么办法解锁应用吗

从 `pm list users` 的结果看，Island 这个 work profile 并没有运行，可以尝试 `am start-user 10` 主动启动它。

**Comment by caseci** [comment]
> > 另外输入HWALP:/ $ dumpsys activity | grep -i run的话,最后会显示 ACTIVITY MANAGER RUNNING PROCESSES (dumpsys activity processes) User #0: state=RUNNING_UNLOCKED User #10: state=RUNNING_LOCKED User #128: state=RUNNING_UNLOCKED
> > 同时如果现在手机上关闭工作模式时输入pm list users Users: UserInfo{0:Owner:13} running UserInfo{10:壶中界:b0} UserInfo{128:分身应用:4000010} running 有什么办法解锁应用吗
> 
> 从 `pm list users` 的结果看，Island 这个 work profile 并没有运行，可以尝试 `am start-user 10` 主动启动它。

这个之前试过
ⅰ当手机工作模式关闭的时候,  am start-user 10
Success: user started
同时pm list users 
user 10 显示变为running,但是手机上显示分身应用并没有解冻,同时提示工作模式已关闭

ⅱ.当手机工作模式开启的时候,pm list users始终是显示running,此时手机上分身应用图标显示解冻但是打开仍然是闪退

同时上面两种情况输入dumpsys activity | grep -i run
都会显示  User #10: state=RUNNING_LOCKED
就是说user 10 处在一个runing但是locked的状态
同时之前每次开启工作模式弹出的需要输入锁屏密码界面的步骤也没了, 使得这种开启工作空间的过程不完整 就像是假的一样,没有真正解锁user 10的用户资料

**Comment by caseci** [comment]
按理说之前开启工作模式的时候都是会触发拉取一个输入锁屏密码的步骤的, 但是现在并没有这一步就直接显示工作模式已开启, 但是其中的分身应用和数据并没有解锁, 同时这样开启工作模式后主用户owner也无法进行除了解锁屏幕以外 一切应用中需要输入锁屏密码来进行验证的操作, 比如开启密码保险箱 chrome导出密码 更改指纹等等中跳出的要求输入锁屏密码的步骤中都是输入点击确定后就闪退

**Comment by caseci** [comment]
![Screenshot_20220108_121239_com android settings](https://user-images.githubusercontent.com/97275740/148631526-5d27d7c5-b2cd-4e23-b883-a3e12f7989c8.png)
手机上有这么一个选项开着, 当工作模式关闭时我尝试关闭它就会提示工作模式已关闭,当我开启工作模式尝试关闭它的时候就会提示要求我输入锁屏密码,然而输入之后点击确定就会闪退

正在考虑是不是可以关掉锁屏密码试试
