### ISSUE TITLE
java.lang.SecurityException: Calling identity is not authorized

### ISSUE THREAD

**Issue by Pervases** [oasisfeng/island#355]
Hi, I have freshly rooted, clean-slate POCO X3 Pro with MIUI Global 13.0.4 Stable (SJUMIXM). When I run the
`adb shell dpm set-profile-owner --user 0 --name Mainland com.oasisfeng.island/.IslandDeviceAdminReceiver`,
I get the following error.

`Exception occurred while executing 'set-profile-owner':
java.lang.SecurityException: Calling identity is not authorized
        at com.android.internal.util.Preconditions.checkCallAuthorization(Preconditions.java:247)
        at com.android.server.devicepolicy.DevicePolicyManagerService.setActiveAdmin(DevicePolicyManagerService.java:3422)
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetProfileOwner(DevicePolicyManagerServiceShellCommand.java:283)
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:91)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:9733)
        at android.os.Binder.shellCommand(Binder.java:953)
        at android.os.Binder.onTransact(Binder.java:837)
        at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6952)
        at android.os.Binder.execTransactInternal(Binder.java:1187)
        at android.os.Binder.execTransact(Binder.java:1146)`

I have already enabled USB debugging (Security settings) to be sure but I still get the error.

**Comment by zubair1836** [comment]
So, was it solved? If so, How?

**Comment by feelgood4** [comment]
For xiaomi secure settings enable as in link 

https://tasker.joaoapps.com/userguide/en/help/ah_device_owner.html
