### ISSUE TITLE
Issue when running dpm set-profile-owner on android 14

### ISSUE THREAD

**Issue by brizaldi** [oasisfeng/island#477]
Running this command on android 14 returns an `IllegalArgumentException` error, seems like on the newest version of dpm the `--name` argument for `set-profile-owner` was removed.
```bash
dpm set-profile-owner --user 0 --name Mainland com.oasisfeng.island/.IslandDeviceAdminReceiver
```

output:
```
java.lang.IllegalArgumentException: Unknown option: --name
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.parseArgs(DevicePolicyManagerServiceShellCommand.java:358)
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetProfileOwner(DevicePolicyManagerServiceShellCommand.java:284)
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:89)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:11422)
        at android.os.Binder.shellCommand(Binder.java:1071)
        at android.os.Binder.onTransact(Binder.java:888)
        at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6340)
        at android.os.Binder.execTransactInternal(Binder.java:1337)
        at android.os.Binder.execTransact(Binder.java:1278)
```

**Comment by G0tta-git-git** [comment]
Facing the same issue. It's still there based on the adb documentation, though.

https://developer.android.com/tools/adb#dpm

**Comment by mabequinho** [comment]
apparently it works despite the error message.
GenesisOS A14.

**Comment by 955whynot** [comment]
the same issue, but it's actually executed already though, just restart island in your phone and  you'll find it's managed now.

**Comment by SteveTinkers** [comment]
I got the same error message, and it did NOT work for me.  I restarted island and it's not Managed Mainland...

I did get it working by removing --name Mainland from the command though.  

Enabling Managed Mainland removes Developer Options????  Choices choices... I need dev options and wireless debugging for adb

**Comment by yqs112358** [comment]
The same problem. Any solution here?

**Comment by OregD** [comment]
this problem is typically when you already have an account on your phone, try this:
1. delete island and reboot (if you already installed)
2. install the app but don't open it.
3. grant your island app "Admin Permission" can be done with adb command
`adb shell dpm set-active-admin com.oasisfeng.island/.IslandDeviceAdminReceiver`
4. open the app and finish the setting.

it's work for me

**Comment by RohanFarseer** [comment]
Leaving this here for anyone who runs into this issue. 
It's literally a typo/syntax error on the part of the dev, specifically the way they posted the command line. 

It _Should_ be:


"dpm set-profile-owner --user 0 com.oasisfeng.island/.IslandDeviceAdminReceiver" 

(no quotes) 

Hope this helps.

**Comment by mahfuzorr489-pixel** [comment]
adb shell dpm set-active-admin com.oasisfeng.island/.IslandDeviceAdminReceiver
