### ISSUE TITLE
FX File Explored crashed in island on a Sony 9210 phone with Android 10

### ISSUE THREAD

**Issue by yanggq** [oasisfeng/island#67]
Hi,
I've installed Island sucessfully on my Sony 9210 (Xperia 5), which just upgraded to Android 10.
Everything was OK except that FX File Explorer v8.0.1.0 can not be started inside Island, while FX works well outside Island. I'm sure it was OK  under Android 9 , before upgrade to Android 10.

I've tried older version, v7.2.2.2 , of FX, but didn't work either.
The following are the logs when it crashes.
Any help would be appreciated !
----------------------------------------------------------------------------

02-18 17:56:51.623  7257  7257 D Analytics: Event: action_launch Bundle[{item_id=nextapp.fx}]
02-18 17:56:51.628  1553  5718 I ActivityTaskManager: START u11 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=nextapp.fx/.ui.ExplorerActivity} from uid 10233
02-18 17:56:51.668  1553  1643 I ActivityManager: Start proc 28520:nextapp.fx/u11a237 for activity {nextapp.fx/nextapp.fx.ui.ExplorerActivity}
02-18 17:56:51.673 28520 28520 E nextapp.fx: Not starting debugger since process cannot load the jdwp agent.
02-18 17:56:51.710 28520 28543 E nextapp.cat: Initializer not found: nextapp.fx.plus.share.connect.TestServer
02-18 17:56:51.719 28520 28546 E nextapp.cat: Initializer not found: nextapp.fx.dir.optionstore.Defaults
02-18 17:56:51.734 28520 28551 E Perf    : Fail to get file list nextapp.fx
02-18 17:56:51.734 28520 28551 E Perf    : Fail to get file list nextapp.fx
02-18 17:56:51.734 28520 28551 E Perf    : Fail to get file list nextapp.fx
02-18 17:56:51.794 28520 28520 E AndroidRuntime: Process: nextapp.fx, PID: 28520
02-18 17:56:51.794 28520 28520 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {nextapp.fx/nextapp.fx.ui.ExplorerActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.permissioncontroller (has extras) }
02-18 17:56:51.794 28520 28520 E AndroidRuntime:        at nextapp.fx.ui.ExplorerActivity.Y(Unknown Source:17)
02-18 17:56:51.794 28520 28520 E AndroidRuntime:        at nextapp.fx.ui.ExplorerActivity.s(Unknown Source:25)
02-18 17:56:51.794 28520 28520 E AndroidRuntime:        at nextapp.fx.ui.content.oa.onResume(Unknown Source:23)
02-18 17:56:51.794 28520 28520 E AndroidRuntime:        at nextapp.fx.ui.ExplorerActivity.onResume(Unknown Source:0)
02-18 17:56:51.795  1553  2386 D ActivityManager: New dropbox entry: nextapp.fx, data_app_crash, 67ac9c33-ade3-4644-a8e2-7b0c784af705
02-18 17:56:51.795  1553  2386 W ActivityTaskManager:   Force finishing activity nextapp.fx/.ui.ExplorerActivity
02-18 17:56:51.797 28520 28560 W nextapp.fx: Failed to query media count: content://media/external/images/media
02-18 17:56:51.797 28520 28560 W nextapp.fx: java.lang.IllegalArgumentException: Invalid column COUNT(DISTINCT(bucket_id))
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at android.content.ContentResolver.query(ContentResolver.java:946)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at android.content.ContentResolver.query(ContentResolver.java:881)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at android.content.ContentResolver.query(ContentResolver.java:837)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at nextapp.fx.media.p.a(Unknown Source:12)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at nextapp.fx.media.p.a(Unknown Source:1)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at nextapp.fx.plus.d.d.b(Unknown Source:22)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at nextapp.fx.plus.ui.ImageHomeItem.a(Unknown Source:24)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at nextapp.fx.ui.homemodel.StaticHomeSection.a(Unknown Source:21)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at nextapp.fx.plus.ui.PlusRegistry$PlusHomeSection.a(Unknown Source:12)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at nextapp.fx.ui.homemodel.g.b(Unknown Source:21)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at nextapp.fx.ui.homecontent.HomeContentView.a(Unknown Source:2)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at nextapp.fx.ui.homecontent.m.run(Unknown Source:4)
02-18 17:56:51.797 28520 28560 W nextapp.fx:    at java.lang.Thread.run(Thread.java:919)
02-18 17:56:51.799  1553  1621 I ActivityManager: Showing crash dialog for package nextapp.fx u11
02-18 17:56:51.803  1201  1201 I JavaDumper:JavaDumperThread: addEvent: data_app_crash@1582019811802.txt processName: nextapp.fx
02-18 17:56:52.296  1553  1625 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{6068c77 u11 nextapp.fx/.ui.ExplorerActivity t1100032 f}
02-18 17:56:52.297  1553  1625 W ActivityTaskManager: Activity pause timeout for ActivityRecord{6068c77 u11 nextapp.fx/.ui.ExplorerActivity t1100032 f}
02-18 17:56:53.588  1553  2386 W ActivityTaskManager:   Force finishing activity nextapp.fx/.ui.ExplorerActivity
02-18 17:56:53.593  1553  6040 E InputDispatcher: Window handle Window{e63f93b u0 Application Error: nextapp.fx} has no registered input channel
02-18 17:56:53.596  1553  2386 I ActivityManager: Killing 28520:nextapp.fx/u11a237 (adj 900): crash
02-18 17:56:53.623  1553  3286 D WifiP2pService: Client:nextapp.fx is removed

**Comment by yanggq** [comment]
Sorry about that! I should have noticed that the system app "App permission" not cloned inside island,  so that the Fx.File explorer can not pop up the permission request.
 Now it works, but still can NOT across users profile and access files outside Island.
