### ISSUE TITLE
Android 11 can't create user

### ISSUE THREAD

**Issue by 4ft35t** [oasisfeng/island#70]
Device: pixel2 with RPP1.200123.016

Island setup with Android 10, after upgrade to Android 11, Island works fine.

After active the God mode, launch Island but don't create work profile.
Then manual setup

```bash
pm create-user --profileOf 0 --managed Island
Error: android.os.ServiceSpecificException: Cannot add user: no_add_managed_profile is enabled. (code 1)
Error: couldn't create User.
```
In the document https://developer.android.com/reference/android/os/UserManager#DISALLOW_ADD_MANAGED_PROFILE
> DISALLOW_ADD_MANAGED_PROFILE
Added in API level 26
Deprecated in API level R
public static final String DISALLOW_ADD_MANAGED_PROFILE
__This constant was deprecated in API level R.__
As the ability to have a managed profile on a fully-managed device has been removed from the platform, this restriction will be silently ignored when applied by the device owner.

**Comment by oasisfeng** [comment]
激活 God mode 后，请在 Island 内创建新空间（Android P 之后 God mode 已无法再通过 ADB 创建空间）。

如果创建失败，请提供 logcat 以便分析。

**Comment by 4ft35t** [comment]
God mode 激活
```bash
walleye:/ $ dpm set-device-owner com.oasisfeng.island/.IslandDeviceAdminReceiver
Success: Device owner set to package ComponentInfo{com.oasisfeng.island/com.oasisfeng.island.IslandDeviceAdminReceiver}
Active admin set to component {com.oasisfeng.island/com.oasisfeng.island.IslandDeviceAdminReceiver}
```
等几分钟后进入 app，只有主空间，没有 Island 空间
![](https://tva1.sinaimg.cn/large/0082zybpgy1gc4zpljcjaj30u01hcwge.jpg)

adb 日志
```log
02-22 10:42:15.160  2323  2323 E asisfeng.islan: Not starting debugger since process cannot load the jdwp agent.
02-22 10:42:15.216  2323  2323 I asisfeng.islan: The ClassLoaderContext is a special shared library.
02-22 10:42:15.220  2323  2323 I asisfeng.islan: The ClassLoaderContext is a special shared library.
02-22 10:42:15.223  2323  2323 W asisfeng.islan: Insufficient pre-allocated space to mmap vdex.
02-22 10:42:15.265  2323  2323 D AppListProvider: Provider created.
02-22 10:42:15.271  2323  2323 I ManualProvisioningReceiver: Device owner changed.
02-22 10:42:17.681  2323  2323 I Island.Main: Profile not setup yet
02-22 10:42:17.721  2323  2323 D skia    : Warning: an opaque image should be decoded as opaque - it is being decoded as non-opaque, which will draw slower
02-22 10:42:17.754  2323  2395 I Adreno GLES: QUALCOMM build                   : 641b27b, Id352e9e033
02-22 10:42:17.754  2323  2395 I Adreno GLES: Build Date                       : 05/27/19
02-22 10:42:17.754  2323  2395 I Adreno GLES: OpenGL ES Shader Compiler Version: EV031.26.13.00
02-22 10:42:17.754  2323  2395 I Adreno GLES: Local Branch                     : 
02-22 10:42:17.754  2323  2395 I Adreno GLES: Remote Branch                    : 
02-22 10:42:17.754  2323  2395 I Adreno GLES: Remote Branch                    : 
02-22 10:42:17.754  2323  2395 I Adreno GLES: Reconstruct Branch               : 
02-22 10:42:17.754  2323  2395 I Adreno GLES: Build Config                     : S L 8.0.7 AArch64
02-22 10:42:17.757  2323  2395 I Adreno GLES: PFP: 0x005ff110, ME: 0x005ff066
02-22 10:42:17.774  2323  2395 I Gralloc4: mapper 4.x is not supported
02-22 10:42:17.774  2323  2395 W Gralloc3: mapper 3.x is not supported
02-22 10:42:17.871  2323  2323 W InputMethodManager: Ignoring onBind: cur seq=1458, given seq=1457
02-22 10:42:17.873  2323  2323 I GAv4    : Google Analytics 12.4.51 is starting up. To enable debug logging on a device run:
02-22 10:42:17.873  2323  2323 I GAv4    :   adb shell setprop log.tag.GAv4 DEBUG
02-22 10:42:17.873  2323  2323 I GAv4    :   adb logcat -s GAv4
02-22 10:42:17.881  2323  2405 W GAv4    : CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions.
02-22 10:42:17.908  2323  2323 I CrashlyticsCore: Initializing Crashlytics 2.6.7.30
02-22 10:42:17.933  2323  2412 I FA      : App measurement is starting up, version: 14710
02-22 10:42:17.933  2323  2412 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-22 10:42:17.934  2323  2412 I FA      : To enable faster debug mode event logging run:
02-22 10:42:17.934  2323  2412 I FA      :   adb shell setprop debug.firebase.analytics.app com.oasisfeng.island
02-22 10:42:17.940  2323  2412 E FA      : AppMeasurementReceiver not registered/enabled
02-22 10:42:17.941  2323  2412 E FA      : Uploading is not possible. App measurement disabled
02-22 10:42:21.136  2323  2412 I FA      : Tag Manager is not found and thus will not be used
02-22 10:42:22.387  2323  2323 I Island.Main: Profile not setup yet
02-22 10:42:42.724  2323  2323 I ManualProvisioningReceiver: Device owner changed.
02-22 10:42:42.780  2323  2636 D Analytics: Event: device_provision_manual_start
02-22 10:44:01.636  2323  2323 D MPSharedPrefs: Tracking shared preferences: app.scope
02-22 10:44:01.664  2323  2323 E asisfeng.islan: Invalid ID 0x00000000.
02-22 10:44:01.670  2323  2323 I chatty  : uid=10211(com.oasisfeng.island) identical 2 lines
02-22 10:44:01.671  2323  2323 E asisfeng.islan: Invalid ID 0x00000000.
02-22 10:44:01.694  2323  2323 D Island.Apps: Primary filter: Mainland
02-22 10:44:01.725  2323  2323 D Island.AppListProv: Start loading apps...
02-22 10:44:01.742  2323  2323 D Island.Apps: Primary filter: Mainland
02-22 10:44:01.761  2323  2323 D Island.Apps: Primary filter: Mainland
02-22 10:44:01.823  2323  2693 D skia    : Warning: an opaque image should be decoded as opaque - it is being decoded as non-opaque, which will draw slower
02-22 10:44:01.833  2323  2693 W asisfeng.islan: resources.arsc in APK '/data/app/hk.alipay.wallet-mFE86X_ryKpgfKztL0V50A==/base.apk' is compressed.
02-22 10:44:01.838  2323  2693 D skia    : Warning: an opaque image should be decoded as opaque - it is being decoded as non-opaque, which will draw slower
02-22 10:44:01.900  2323  2693 W asisfeng.islan: resources.arsc in APK '/data/app/dji.mimo-i64IaugboPUO_SdwHU8nWQ==/base.apk' is compressed.
02-22 10:44:16.874  2323  2395 D OpenGLRenderer: endAllActiveAnimators on 0x7245197d00 (MenuPopupWindow$MenuDropDownListView) with handle 0x7247944160
02-22 10:44:25.674  2323  2323 W asisfeng.islan: resources.arsc in APK '/data/app/hk.alipay.wallet-mFE86X_ryKpgfKztL0V50A==/base.apk' is compressed.
02-22 10:44:25.789  2323  2323 W asisfeng.islan: resources.arsc in APK '/data/app/com.tencent.wework-4Y-PbsCCKRMKUml34cUFTg==/base.apk' is compressed.
02-22 10:44:28.035  2323  2323 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.

```

**Comment by horganizzato** [comment]
I'm having the same problem. Godmode works no problem for managing Mainland apps. 

Problem: Can't create a sandboxed "island" for untrusted apps.

`[hocine@new-host-2 ~] $ adb shell
walleye:/ $ pm create-user --profileOf 0 --managed Island
Error: android.os.ServiceSpecificException: Cannot add user: no_add_managed_profile is enabled. (code 1)
Error: couldn't create User.
`

**Comment by livelazily** [comment]
Android 11 正式版, Island v4.5.4 device-owner, 同样的问题.
logcat 如下:
```
~ ❯❯❯ adb logcat -c
~ ❯❯❯ adb logcat
--------- beginning of main
09-09 13:41:31.167  3122 29462 W clrj    : [{0}] Failed to resolve name. status={1}
--------- beginning of system
09-09 13:41:33.663  1392  1552 I DevicePolicyManager: Adding a profile is restricted: User UserHandle{0} Has device owner? true
09-09 13:41:33.665 29124 29124 D Analytics: Event: setup_island_failure Bundle[{item_category=managed_device, item_id=com.oasisfeng.island}]
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: IntentStarted during UNKNOWN. Intent { act=android.intent.action.VIEW dat=https://island.oasisfeng.com/... (has extras) sel=act=android.intent.action.MAIN cat=[android.intent.category.APP_BROWSER]} }
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: java.lang.Throwable: EventSequenceValidator#getStackTrace
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: 	at com.google.android.startop.iorap.EventSequenceValidator.logWarningWithStackTrace(EventSequenceValidator.java:260)
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: 	at com.google.android.startop.iorap.EventSequenceValidator.onIntentStarted(EventSequenceValidator.java:106)
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: 	at com.android.server.wm.LaunchObserverRegistryImpl.handleOnIntentStarted(LaunchObserverRegistryImpl.java:139)
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: 	at com.android.server.wm.LaunchObserverRegistryImpl.lambda$veRn_GhgLZLlOHOJ0ZYT6KcfYqo(Unknown Source:0)
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: 	at com.android.server.wm.-$$Lambda$LaunchObserverRegistryImpl$veRn_GhgLZLlOHOJ0ZYT6KcfYqo.accept(Unknown Source:10)
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:292)
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: 	at android.os.Handler.handleCallback(Handler.java:938)
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: 	at android.os.Looper.loop(Looper.java:223)
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: 	at android.os.HandlerThread.run(HandlerThread.java:67)
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
09-09 13:41:33.669  1392  1462 D EventSequenceValidator: inc AccIntentStartedEvents to 2
09-09 13:41:33.670  1392  1411 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=https://island.oasisfeng.com/... cmp=android/com.android.internal.app.ResolverActivity (has extras) sel=act=android.intent.action.MAIN cat=[android.intent.category.APP_BROWSER]}} from uid 10369
09-09 13:41:33.672   671   671 D android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 1
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: onActivityLaunched during UNKNOWN.
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: java.lang.Throwable: EventSequenceValidator#getStackTrace
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: 	at com.google.android.startop.iorap.EventSequenceValidator.logWarningWithStackTrace(EventSequenceValidator.java:260)
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: 	at com.google.android.startop.iorap.EventSequenceValidator.onActivityLaunched(EventSequenceValidator.java:149)
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: 	at com.android.server.wm.LaunchObserverRegistryImpl.handleOnActivityLaunched(LaunchObserverRegistryImpl.java:157)
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: 	at com.android.server.wm.LaunchObserverRegistryImpl.lambda$UGY1OclnLIQLMEL9B55qjERFf4o(Unknown Source:0)
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: 	at com.android.server.wm.-$$Lambda$LaunchObserverRegistryImpl$UGY1OclnLIQLMEL9B55qjERFf4o.accept(Unknown Source:10)
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:292)
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: 	at android.os.Handler.handleCallback(Handler.java:938)
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: 	at android.os.Looper.loop(Looper.java:223)
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: 	at android.os.HandlerThread.run(HandlerThread.java:67)
09-09 13:41:33.676  1392  1462 D EventSequenceValidator: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
09-09 13:41:33.677  1392  3416 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (1169806)
09-09 13:41:33.781  1392  1552 I chatty  : uid=1000(system) Binder:1392_3 identical 3 lines
09-09 13:41:33.781  1392  1552 E IntervalStats: Unable to parse event package 7
09-09 13:41:33.781  1392  1552 E IntervalStats: Unable to parse event package 72
09-09 13:41:33.781  1392  1552 E IntervalStats: Unable to parse event package 7
09-09 13:41:33.798 27924 27944 D AbstractResolverComp: Setting watchdog timer for 500ms
09-09 13:41:33.855 27924 27924 D AbstractResolverComp: RANKER_SERVICE_RESULT
09-09 13:41:33.861  1392  1467 D ArtManagerInternalImpl: /data/misc/iorapd/android/30/com.android.internal.app.ResolverActivity/compiled_traces/compiled_trace.pb exists
09-09 13:41:33.861  1392  1467 D ArtManagerInternalImpl: /data/misc/iorapd/android/30/com.android.internal.app.ResolverActivity/compiled_traces/compiled_trace.pb size is 5599
09-09 13:41:33.862  1392  1467 I ActivityTaskManager: Displayed android/com.android.internal.app.ResolverActivity: +190ms
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: onActivityLaunchFinished during UNKNOWN.
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: java.lang.Throwable: EventSequenceValidator#getStackTrace
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: 	at com.google.android.startop.iorap.EventSequenceValidator.logWarningWithStackTrace(EventSequenceValidator.java:260)
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: 	at com.google.android.startop.iorap.EventSequenceValidator.onActivityLaunchFinished(EventSequenceValidator.java:185)
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: 	at com.android.server.wm.LaunchObserverRegistryImpl.handleOnActivityLaunchFinished(LaunchObserverRegistryImpl.java:175)
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: 	at com.android.server.wm.LaunchObserverRegistryImpl.lambda$QcawcFcJtEX4EhYptq_Vb4j368Y(Unknown Source:0)
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: 	at com.android.server.wm.-$$Lambda$LaunchObserverRegistryImpl$QcawcFcJtEX4EhYptq_Vb4j368Y.accept(Unknown Source:10)
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:292)
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: 	at android.os.Handler.handleCallback(Handler.java:938)
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: 	at android.os.Looper.loop(Looper.java:223)
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: 	at android.os.HandlerThread.run(HandlerThread.java:67)
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
09-09 13:41:33.866  1392  1462 D EventSequenceValidator: dec AccIntentStartedEvents to 1
09-09 13:41:33.897 27924 27924 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{org.bromite.bromite/com.google.android.apps.chrome.Main}, intent component: ComponentInfo{org.bromite.bromite/com.google.android.apps.chrome.Main}
09-09 13:41:33.897 27924 27924 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{com.android.chrome/com.google.android.apps.chrome.Main}, intent component: ComponentInfo{com.android.chrome/com.google.android.apps.chrome.Main}
09-09 13:41:33.942 25088 25088 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3184
09-09 13:41:33.943 25088 25088 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1830
09-09 13:41:34.191   671   671 D android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 0
09-09 13:41:48.339   974  1004 I CHRE    : @ 1323.694: [ImuCal] [NanoSensorCal:GYRO_RPS] Offset | Temperature [C]: 0.010671, -0.003472, -0.013292 | 27.88
09-09 13:41:48.340   974  1004 I CHRE    : @ 1323.694: [ImuCal] [NanoSensorCal:GYRO_RPS] Temp Sensitivity: 0.000273, -0.000261, -0.000635
09-09 13:41:48.340   974  1004 I CHRE    : @ 1323.694: [ImuCal] [NanoSensorCal:GYRO_RPS] Temp Intercept: 0.004206, 0.002742, 0.004518
09-09 13:41:51.424   887   887 I android.hardware.health@2.0-service.wahoo: SRAM data: 3699000
09-09 13:41:33.784  1392  1552 I chatty  : uid=1000(system) Binder:1392_3 identical 55 lines
09-09 13:41:33.784  1392  1552 E IntervalStats: Unable to parse event package 7
09-09 13:41:51.443  1809  4519 D PowerUI : can't show warning due to - plugged: true status unknown: false
09-09 13:42:48.375   974  1004 I CHRE    : @ 1383.728: [ImuCal] [NanoSensorCal:GYRO_RPS] Offset | Temperature [C]: 0.010535, -0.003342, -0.012976 | 27.38
09-09 13:42:48.377   974  1004 I CHRE    : @ 1383.728: [ImuCal] [NanoSensorCal:GYRO_RPS] Temp Sensitivity: 0.000273, -0.000261, -0.000635
09-09 13:42:48.377   974  1004 I CHRE    : @ 1383.728: [ImuCal] [NanoSensorCal:GYRO_RPS] Temp Intercept: 0.004206, 0.002742, 0.004518
09-09 13:42:51.424   887   887 I android.hardware.health@2.0-service.wahoo: SRAM data: 3699000
09-09 13:42:51.441  1809  4060 D PowerUI : can't show warning due to - plugged: true status unknown: false
```

**Comment by huangsijun17** [comment]
> 激活 God mode 后，请在 Island 内创建新空间（Android P 之后 God mode 已无法再通过 ADB 创建空间）。
> 
> 如果创建失败，请提供 logcat 以便分析。

logcat如何提供？

**Comment by proletarius101** [comment]
A possible solution: use diamond mode

**Comment by oasisfeng** [comment]
Issue confirmed on Android 11, working to find a solution.

**Comment by bluehomewu** [comment]
> Issue confirmed on Android 11, working to find a solution.

Used Havoc OS 4.0 Android 11 for ASUS ZenFone 5 (2018) X00QD, there's no issue.Works fine.

**Comment by oasisfeng** [comment]
> Used Havoc OS 4.0 Android 11 for ASUS ZenFone 5 (2018) X00QD, there's no issue.Works fine.

I think it's already blocked in Android 11 r1, as of this commit in AOSP:
https://github.com/aosp-mirror/platform_frameworks_base/commit/6ad0e194d7195ee4d06bb32b966057ea15e3e563

**Comment by oasisfeng** [comment]
> A possible solution: use diamond mode

If you mean "Demigod mode", yes, that's a viable alternative solution.

**Comment by proletarius101** [comment]
> > A possible solution: use diamond mode
> 
> If you mean "Demigod mode", yes, that's a viable alternative solution.

Yes. Typo. ;)

**Comment by Flunkyball** [comment]
Is there a solution to this problem available ?
Iam stuck with the same thing on a Galaxy S20 with Android 11.
`
pm create-user --profileOf 0 --managed Island`
results in "Error: couldn’t create User"

`getprop fw.max_users`
Shows a set value of 10.

**Comment by abhishekgupta92** [comment]
> Is there a solution to this problem available ?
> Iam stuck with the same thing on a Galaxy S20 with Android 11.
> ` pm create-user --profileOf 0 --managed Island`
> results in "Error: couldn’t create User"
> 
> `getprop fw.max_users`
> Shows a set value of 10.

I'm also stuck at the same issue. I'm using Android 10, Samsung Galaxy M31s.

**Comment by sorat0mo** [comment]
Pixel 5a, Graphene OS, issue confirmed, no way to manually configure new islands.

**Comment by FurriousFox** [comment]
Have the same issue too, I chose for god mode cause Demigod mode had "You can no longer create new Island space after Demigod is activated. It’s suggested to setup Island space before activating Demigod mode." but with god mode, you can't even have one at all.

But I don't want to go through the hassle of removing all accounts again.

**Comment by FurriousFox** [comment]
I also can't use the dual app feature of the default ROM anymore, so I think I'm forced to redo this fully again and choose Demigod mode.
I guess there isn't any way to easily switch to Demigod without removing and re-adding all accounts.

**Comment by guschc** [comment]
Interesting fact: All of this works when Samsung FBE device encryption is not used. So if you have a rooted phone and re-setup it without encryption (e.g. by flashing multidisabler), Island will install just fine with the root routine of the app.
If the phone is encrypted, the step 1 error comes up, and user creation via ADB doesn't work either.

Very weird.

**Comment by george2781** [comment]
I'm having this problem as well.

**Comment by PixelCode01** [comment]
Is there any solution for this

**Comment by ssktowtw** [comment]
![image](https://github.com/oasisfeng/island/assets/43614305/81175b40-c938-45d3-a661-e9d28ba1977e)
https://xdaforums.com/t/app-5-0-beta-island-app-freezing-privacy-protection-parallel-accounts.3366295/

not use  **pm install-existing --user <user id> com.oasisfeng.island**

use  **pm install -r /data/app/com.oasisfeng.island-1/base.apk**
