### ISSUE TITLE
上帝模式導致S8+死機

### ISSUE THREAD

**Issue by jasonwu1994** [oasisfeng/island#75]
開了上帝模式後重開機 直接死機，無言
從TWRP移除MAGISK也沒用，整個系統廢了
完全進不去

**Comment by oasisfeng** [comment]
很抱歉，目前手上没有三星手机可以重现这个问题，现已在文档中加入对三星设备的警告。
https://github.com/oasisfeng/island/blob/gh-pages/setup.md#manual-setup-for-island-in-god-mode

谢谢反馈！

**Comment by oasisfeng** [comment]
请尝试新的 Demigod mode（替代 God mode）：
https://github.com/oasisfeng/island/blob/gh-pages/setup.md#manual-setup-for-island-in-god-mode--demigod-mode

希望得到关于三星设备上 Demigod mode 兼容性情况的反馈。

**Comment by jasonwu1994** [comment]
S8+ android 9.0 One UI 1.0 乾淨系統，只有裝island測試
magisk 20.4
island 4.5.4

使用root建立 island ->setting->mainland->godmod->重啟->正常獲得權限->可以凍結系統級mainland app

使用root建立 island ->adb->Demigod mode->不用重啟->正常獲得權限->可以凍結系統級mainland app
Success: Active admin and profile owner set to {com.oasisfeng.island/com.oasisfeng.island.IslandDeviceAdminReceiver} for user 0

使用root建立 island ->adb->God mode->錯誤
dpm set-device-owner com.oasisfeng.island/.IslandDeviceAdminReceiver
java.lang.IllegalStateException: Not allowed to set the device owner because there are already several users on the device
        at android.os.Parcel.createException(Parcel.java:1974)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.os.Parcel.readException(Parcel.java:1884)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:6290)
        at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:176)
        at com.android.commands.dpm.Dpm.onRun(Dpm.java:106)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.dpm.Dpm.main(Dpm.java:41)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:341)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8865)
        at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:8023)
        at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:1242)
        at android.os.Binder.execTransact(Binder.java:739)

**Comment by Dimas372** [comment]
set-device-owner com.oasisfeng.island/.IslandDeviceAdminReceiver

**Comment by Zack12357** [comment]
> S8+ android 9.0 One UI 1.0 乾淨系統，只有裝island測試 magisk 20.4
> 
> 使用root建立 island ->setting->mainland->godmod->重啟->正常獲得權限->可以凍結系統級mainland app
> 
> 使用root建立 island ->adb->Demigod mode->不用重啟->正常獲得權限->可以凍結系統級mainland app Success： Active admin and profile owner set to {com.oasisfeng.island.Island.IslandDeviceAdminReceiver} for user 0
> 
> 使用root建立 island ->adb->God mode->錯誤 dpm set-device-owner com.oasisfeng.island/.IslandDeviceAdminReceiver java.lang.IllegalStateException：不允许设置设备所有者，因为在 android.os.Parcel.createException（Parcel.java：1974） at android.os.Parcel.readException（Parcel.java：1934） at android.os.Parcel.readException（Parcel.java：1884） at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner（IDevicePolicyManager.java：6290） at com.android.commands.dpm.dpm.runSetDeviceOwner（Dpm.java：176） at com.android.commands.dpm.dpm.onRun（Dpm.java：106） at com.android.internal.os.BaseCommand.run（BaseCommand.java：54） at com.android.commands.dpm.Dpm.main（Dpm.java：41） at com.android.internal.os.RuntimeInit.nativeFinishInit（Native Method） at com.android.internal.os.RuntimeInit.main（RuntimeInit.java：341） 由以下原因引起：android.os.RemoteException： Remote stack trace： at com.android.server.devicepolicy.DevicePolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked（DevicePolicyManagerService.java：8865） at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner（DevicePolicyManagerService.java：8023） at android.app.admin.IDevicePolicyManager$Stub.onTransact（IDevicePolicyManager.java：1242） atandroid.os.Binder.execTransact（Binder.java：739）

你用秋之盒pc端软件里有一个叫用户管理的按钮就能找出存在的一些隐性的账号直接删除在激活就百分百成功了
